feat: add `inset` option
sindresorhus/capture-website-cli pull request #30
Opened 2021-02-19 00:08 UTC by krnik

2021-02-19 06:10 UTC, sindresorhus requested changes

2021-02-19 06:10 UTC, sindresorhus commented on cli.js
> +	  --inset=10,15,-10,15
Add an example with a single element too.

2021-02-19 06:10 UTC, sindresorhus commented on cli.js
> +		options.inset = ['top', 'right', 'bottom', 'left'].reduce((acc, key, index) => {
I prefer to not use `reduce`. Code is usually more readable with a `for-of` loop.

2021-02-19 06:10 UTC, sindresorhus commented on cli.js
> +	const containsNaN = values.findIndex(number => Number.isNaN(number)) > -1;
`Array#every` would be a better choice here.

2021-02-19 06:10 UTC, sindresorhus commented on cli.js
> +		console.error('The `inset` flag value is invalid, please refer to the flag examples');
```suggestion
		console.error('Invalid `--inset` value');
```

2021-02-19 06:10 UTC, sindresorhus commented on cli.js
> +	  --inset                  Set the inset of the screenshot relative to the viewport or \`--element\`. Accepts \`number\` or four comma-separated numbers for top, right, left and bottom values
```suggestion
	  --inset                  Inset the screenshot relative to the viewport or \`--element\`. Accepts a number or four comma-separated numbers for top, right, left, and bottom.
```

2021-02-20 07:27 UTC, sindresorhus commented
The readme and the actual CLI output are not in sync.

2021-02-20 10:51 UTC, krnik commented
Right, I missed this change. Should be synced now.

2021-02-20 12:59 UTC, merged